## Inverse Kinematics Simple Example

In [14]:
import matplotlib.pyplot as plt
import numpy as np
from numpy import sin, cos, tan, pi
import robotics
from robotics import Rz, Ry, Rz, sind, cosd, DH, prettymat, HTinv
rtd = 180/pi
dtr = pi/180

<img src="https://faculty.gvsu.edu/kraussry/445_images/inverse_kin_sketches/Simple_2_DOF_3_D_Robot_cropped.jpg" width=300px>

## Problem Statement

Given the lengths

In [3]:
A = 10
B = 7

find $\theta_1$ and $\theta_2$ to place the tip of the robot at 
$$^0P_{tip} = \begin{bmatrix} 6.478 \\ 1.142 \\ 12.39\end{bmatrix}$$

- verify your solution with forward kinematics

In [4]:
P_tip_0 = np.array([6.478, 1.142, 12.39])

## Guiding Questions

- what can I learn from a top view?
- what can I learn from a sideview?


## Nagging Question

- is this problem solvable?
    - it seems like I have 2 joints but 3 DOF

## Top View

<img src="https://faculty.gvsu.edu/kraussry/445_images/lecture_slides_images_445/class_13_inv_kin/class_13_inverse_kinematics_part_2_main_markedup_0004.jpg" width=800px>

In [5]:
th1 = np.arctan2(P_tip_0[1], P_tip_0[0])*rtd
th1

np.float64(9.997888252385293)

## Use $\theta_1$ to get to a sideview

<img src="https://faculty.gvsu.edu/kraussry/445_images/lecture_slides_images_445/class_13_inv_kin/class_13_inverse_kinematics_part_2_main_markedup_0005.jpg" width=800px>

In [8]:
T01 = DH(0,0,th1, A)

In [11]:
T10 = robotics.HTinv(T01)
T10

array([[  0.98481415,   0.17361188,   0.        ,  -0.        ],
       [ -0.17361188,   0.98481415,   0.        ,  -0.        ],
       [  0.        ,  -0.        ,   1.        , -10.        ],
       [  0.        ,   0.        ,   0.        ,   1.        ]])

In [15]:
prettymat(T10@T01)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [17]:
P_tip_0 = robotics.append_one(P_tip_0)

In [19]:
P_tip_1 = prettymat(T10@P_tip_0)
P_tip_1

array([6.57789085, 0.        , 2.39      , 1.        ])

In [20]:
th2 = np.arctan2(P_tip_1[2],P_tip_1[0])*rtd
th2

np.float64(19.968024253154127)

## $\theta_2$ alternative route

$$^0P_{tipz} = A + B \sin \theta_2$$

$$\sin \theta_2 = (^0P_{tipz} - A)/B$$ 

In [34]:
sin_th2 = (P_tip_0[2]-A)/B
sin_th2

np.float64(0.3414285714285715)

In [35]:
cos_th2_p = np.sqrt(1-sin_th2**2)
cos_th2_p

np.float64(0.9399077245199365)

In [36]:
th2_alt_pos = np.arctan2(sin_th2, cos_th2_p)*rtd
th2_alt_pos

np.float64(19.96393427789295)

## Verification

In [26]:
P_tip_2 = np.array([B,0,0,1])

In [27]:
T12 = DH(90,0,th2,0)

In [28]:
T02 = T01 @ T12

In [30]:
P_tip_0_check = T02  @ P_tip_2
P_tip_0_check

array([ 6.47927297,  1.14222441, 12.39046965,  1.        ])

In [31]:
P_tip_0

array([ 6.478,  1.142, 12.39 ,  1.   ])

In [32]:
check = P_tip_0 - P_tip_0_check
check

array([-0.00127297, -0.00022441, -0.00046965,  0.        ])