## Inverse Kinematics Simple Example 2

In [8]:
import matplotlib.pyplot as plt
import numpy as np
from numpy import sin, cos, tan, pi
import robotics
from robotics import Rz, Ry, Rz, sind, cosd, DH, HTinv, prettymat
rtd = 180/pi
dtr = pi/180

<img src="https://faculty.gvsu.edu/kraussry/445_images/inverse_kin_sketches/inv_kin_3dof_3d_intro_robot_3.png" width=300px>

## Problem Statement

Given the lengths

In [4]:
A = 9
B = 6

find $\theta_1$, $d_2$, and $\theta_3$ to place the tip of the robot at 
$$^0P_{tip} = \begin{bmatrix} 8.978 \\ 6.256 \\ 10.834\end{bmatrix}$$

- verify your solution using forward kinematics

In [5]:
P_tip_0 = np.array([8.978, 6.256, 10.834])

## $\theta_1$ from top view

In [6]:
th1 = np.arctan2(P_tip_0[1],P_tip_0[0])*rtd
th1

np.float64(34.86934053591355)

## Need Side View: $^1P_{tip}$

<img src="https://faculty.gvsu.edu/kraussry/445_images/lecture_slides_images_445/class_13_inv_kin/class_13_inverse_kinematics_part_2_main_markedup_0007.jpg" width=800px>

**DH Note 1:** $\hat{X}_1$ needs to be perpendicular to the $\hat{Z}_1/\hat{Z}_2$ plane, so we need $\pm90^\circ$ in our DH table

In [10]:
T01 = DH(0,0,th1+90,A)
T01

array([[-0.57170692, -0.82045792,  0.        ,  0.        ],
       [ 0.82045792, -0.57170692, -0.        , -0.        ],
       [ 0.        , -0.        ,  1.        ,  9.        ],
       [ 0.        ,  0.        ,  0.        ,  1.        ]])

In [11]:
T10 = HTinv(T01)

In [13]:
P_tip_0 = robotics.append_one(P_tip_0)

In [16]:
P_tip_1 = prettymat(T10 @ P_tip_0)
P_tip_1

array([  0.        , -10.94266969,   1.834     ,   1.        ])

In [17]:
r = np.sqrt(P_tip_0[0]**2 + P_tip_0[1]**2)
r

np.float64(10.942669692538471)

In [18]:
opp_th3 = P_tip_1[2]
opp_th3

np.float64(1.8339999999999996)

In [19]:
adj_th3 = np.sqrt(B**2 - opp_th3**2)
adj_th3

np.float64(5.712831522108805)

In [20]:
th3 = np.arctan2(opp_th3, adj_th3)*rtd
th3

np.float64(17.798276656924635)

In [21]:
d2 = r - B*cosd(th3)
d2

np.float64(5.229838170429667)

## Verification

In [23]:
T12 = DH(90,0,90,d2)

In [29]:
T23 = DH(-90,0,th3,0)

**DH Note 2:** If we simply have $\theta_3$ without any offsets in our DH table, then $^3P_{tip}$ is actually in the negative $\hat{Y}_3$ direction:

In [38]:
P_tip_3 = np.array([0,-B,0,1])

In [39]:
P_tip_0_check = T01 @ T12 @ T23 @ P_tip_3
P_tip_0_check

array([ 8.978,  6.256, 10.834,  1.   ])

In [40]:
P_tip_0

array([ 8.978,  6.256, 10.834,  1.   ])

## Alternative Frame 3 

As an alternative to $^3P_{tip}$ being in the negative $\hat{Y}_3$ direction, we could use an offest in our DH table to point $\hat{X}_3$ at the tip:

In [41]:
T23_alt = DH(-90,0,th3-90,0)

In [42]:
P_tip_3_alt = np.array([B,0,0,1])

In [43]:
P_tip_0_alt = T01 @ T12 @ T23_alt @ P_tip_3_alt
P_tip_0_alt

array([ 8.978,  6.256, 10.834,  1.   ])

## Other checks

In [33]:
B*sind(th3) + A

np.float64(10.834)

In [34]:
B*cosd(th3) + d2

np.float64(10.942669692538471)

In [35]:
r

np.float64(10.942669692538471)

In [36]:
P_tip_1

array([  0.        , -10.94266969,   1.834     ,   1.        ])

In [37]:
T01 @ P_tip_1

array([ 8.978,  6.256, 10.834,  1.   ])