In [8]:
import matplotlib.pyplot as plt
import numpy as np
from numpy import sin, cos, tan, pi
import robotics
from robotics import Rx, Ry, Rz, sind, cosd, DH, prettymat
rtd = 180/pi
dtr = pi/180

In [2]:
col1 = [0,0,1]
col2 = [-sind(40),-cosd(40),0]
col3 = [sind(50), -cosd(50), 0]

In [3]:
R_AB = np.column_stack([col1,col2,col3])
R_AB

array([[ 0.        , -0.64278761,  0.76604444],
       [ 0.        , -0.76604444, -0.64278761],
       [ 1.        ,  0.        ,  0.        ]])

In [4]:
P_Borg_A = [12*sind(40), 12*cosd(40),0]

In [5]:
T_AB = robotics.HT_from_R_and_Porg(R_AB, P_Borg_A)
T_AB

array([[ 0.        , -0.64278761,  0.76604444,  7.71345132],
       [ 0.        , -0.76604444, -0.64278761,  9.19253332],
       [ 1.        ,  0.        ,  0.        ,  0.        ],
       [ 0.        ,  0.        ,  0.        ,  1.        ]])

In [9]:
prettymat(R_AB@(R_AB.T))

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [10]:
T_AB.T

array([[ 0.        ,  0.        ,  1.        ,  0.        ],
       [-0.64278761, -0.76604444,  0.        ,  0.        ],
       [ 0.76604444, -0.64278761,  0.        ,  0.        ],
       [ 7.71345132,  9.19253332,  0.        ,  1.        ]])

In [11]:
np.linalg.inv(T_AB)

array([[ 0.        ,  0.        ,  1.        ,  0.        ],
       [-0.64278761, -0.76604444, -0.        , 12.        ],
       [ 0.76604444, -0.64278761,  0.        ,  0.        ],
       [ 0.        ,  0.        ,  0.        ,  1.        ]])

In [12]:
prettymat(T_AB@(T_AB.T))

array([[60.49733121, 70.90615822,  0.        ,  7.71345132],
       [70.90615822, 85.50266879,  0.        ,  9.19253332],
       [ 0.        ,  0.        ,  1.        ,  0.        ],
       [ 7.71345132,  9.19253332,  0.        ,  1.        ]])

In [13]:
prettymat(T_AB@(robotics.HTinv(T_AB)))

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [15]:
prettymat(robotics.HTinv(T_AB))

array([[ 0.        ,  0.        ,  1.        ,  0.        ],
       [-0.64278761, -0.76604444,  0.        , 12.        ],
       [ 0.76604444, -0.64278761,  0.        ,  0.        ],
       [ 0.        ,  0.        ,  0.        ,  1.        ]])