# LA 10 PUMA Wrist Angles

## PUMA YouTube Video

If you aren't sure how the PUMA moves or what the schematic needs to capture, watch this video:
[https://youtu.be/ArzP7rh4_9Q](https://youtu.be/ArzP7rh4_9Q)

Here is a link to Dr. Krauss' YouTube video concerning the PVC PUMA model:
[https://youtu.be/lX0cCZkAzrU](https://youtu.be/lX0cCZkAzrU)

In [2]:
def myarraytest(in1, in2):
    mydiff = np.array(in1) - np.array(in2)
    mymax = np.max(np.abs(mydiff))
    return mymax < 1e-6

In [3]:
import matplotlib.pyplot as plt
import numpy as np
from numpy import sin, cos, tan, pi
import robotics
from robotics import Rx, Ry, Rz, sind, cosd, DH, HTinv, dot_list, prettymat
rtd = 180/pi
dtr = pi/180

<img src="https://faculty.gvsu.edu/kraussry/445_images/puma/puma_pvc_joint_angles.jpeg" width=300px>

<img src="https://faculty.gvsu.edu/kraussry/445_images/puma/puma_sort_of_top_back.jpeg" width=300px>

<img src="https://faculty.gvsu.edu/kraussry/445_images/puma/puma_weird_schematic.jpeg" width=300px>

<img src="https://faculty.gvsu.edu/kraussry/445_images/puma/puma_pvc_in_schematic_position.jpeg" width=300px>

For the PUMA model above, the following lengths are in inches:

In [4]:
A = 16
B = 9
C = 21
D = 3.5
E = 3
F = 11
G = 5

## Dr. Krauss' PUMA DH Table

i|$\alpha$|$a$|$\theta$|d
-|--------|----|--------|-------------
1|0|0|$\theta_1$|A
2|90|0|$\theta_2$|0
3|0|C|$\theta_3$|D-B
4|90|E|th4|F
5|-90|0|th5|0
6|90|0|th6|G

## Problem Statement

Given the HT matrix $^0_{tip}\mathbf{T}$:

In [5]:
T_0_tip = np.array([[-0.04905994, -0.79720351,  0.60171396, 31.60648245],
       [-0.89714672,  0.29996241,  0.32426889, 12.78315737],
       [-0.43899987, -0.52391709, -0.72992465, 16.36523055],
       [ 0.        ,  0.        ,  0.        ,  1.        ]])
T_0_tip

array([[-0.04905994, -0.79720351,  0.60171396, 31.60648245],
       [-0.89714672,  0.29996241,  0.32426889, 12.78315737],
       [-0.43899987, -0.52391709, -0.72992465, 16.36523055],
       [ 0.        ,  0.        ,  0.        ,  1.        ]])

### Step 1

First, use the technique outlined in lecture to find the wrist location, $^0P_{wrist}$

In [7]:
P_w2t_6 = np.array([0,0,G])

In [8]:
R06 = T_0_tip[0:3,0:3]
R06

array([[-0.04905994, -0.79720351,  0.60171396],
       [-0.89714672,  0.29996241,  0.32426889],
       [-0.43899987, -0.52391709, -0.72992465]])

In [11]:
P_tip_0 = T_0_tip[0:3,-1]

In [12]:
P_w2t_0 = R06 @ P_w2t_6
P_w2t_0

array([ 3.0085698 ,  1.62134445, -3.64962325])

In [13]:
P_wrist_0 = P_tip_0 - P_w2t_0
P_wrist_0

array([28.59791265, 11.16181292, 20.0148538 ])

In [6]:
P_wrist_0_check = np.array([28.59791263, 11.16181292, 20.01485379])
P_wrist_0_check

array([28.59791263, 11.16181292, 20.01485379])

### Steps 2-N

Assume you found the first three joint angles based on graphical analysis of the top and side views:

In [4]:
th1 = 11
th2 = 22
th3 = 33

- Verify that these three joint angles lead to the correct wrist location $^0P_{wrist}$
- Find $^0_{w}\mathbf{T}$
- Find the joint angles $\theta_4$, $\theta_5$, and $\theta_6$
    - Find $^W_{tip}\mathbf{T}_{num}$
    - Use symbolic forward kinematics to find $^W_{tip}\mathbf{T}_{sym}$
    - Pick out equations to help you find $\theta_4$, $\theta_5$, and $\theta_6$
- Use forward kinematics to verify that you have a valid full solution that leads to $^0_{tip}\mathbf{T}$

In [ ]:
T01 = 
T12 = 
T23 = 
T3W = 

In [14]:
T0W = T01 @ T12 @ T23 @ T3W

NameError: name 'T01' is not defined

## Answers for checking


$^0_{w}\mathbf{T}$:

In [37]:
T_0_wrist_check = np.array([[ 0.56303822,  0.190809  ,  0.80410191, 28.59791263],
       [ 0.10944354, -0.98162718,  0.15630158, 11.16181292],
       [ 0.81915204,  0.        , -0.57357644, 20.01485379],
       [ 0.        ,  0.        ,  0.        ,  1.        ]])
T_0_wrist_check

array([[ 0.56303822,  0.190809  ,  0.80410191, 28.59791263],
       [ 0.10944354, -0.98162718,  0.15630158, 11.16181292],
       [ 0.81915204,  0.        , -0.57357644, 20.01485379],
       [ 0.        ,  0.        ,  0.        ,  1.        ]])

$^W_{tip}\mathbf{T}_{num}$:

In [40]:
T_wrist_tip_check = np.array([[-0.48541718, -0.84519485, -0.22364217, -1.11821086],
       [ 0.87130253, -0.44656486, -0.20349872, -1.0174936 ],
       [ 0.07212534, -0.29364177,  0.95319067,  4.76595334],
       [ 0.        ,  0.        ,  0.        ,  1.        ]])
T_wrist_tip_check

array([[-0.48541718, -0.84519485, -0.22364217, -1.11821086],
       [ 0.87130253, -0.44656486, -0.20349872, -1.0174936 ],
       [ 0.07212534, -0.29364177,  0.95319067,  4.76595334],
       [ 0.        ,  0.        ,  0.        ,  1.        ]])

## Find $^W_{tip}\mathbf{T}$ Symbolic

i|$\alpha$|$a$|$\theta$|d
-|--------|----|--------|-------------
1|0|0|$\theta_1$|A
2|90|0|$\theta_2$|0
3|0|C|$\theta_3$|D-B
4|90|E|th4|F
5|-90|0|th5|0
6|90|0|th6|G

In [15]:
import sympy
import robotics_sympy

In [17]:
th4s, th5s, th6s, Gs = sympy.symbols(["\\theta_4","\\theta_5", "\\theta_6", "G"])
th4s

\theta_4

In [18]:
TW4s = robotics_sympy.DH(0,0,th4s,0)
TW4s

Matrix([
[cos(\theta_4), -sin(\theta_4), 0, 0],
[sin(\theta_4),  cos(\theta_4), 0, 0],
[            0,              0, 1, 0],
[            0,              0, 0, 1]])

## Don't do this

- `sympy` uses radians

In [23]:
T45s_wrong = robotics_sympy.DH(-90,0,th5s,0)
T45s_wrong

Matrix([
[         cos(\theta_5),         -sin(\theta_5),       0, 0],
[ sin(\theta_5)*cos(90),  cos(90)*cos(\theta_5), sin(90), 0],
[-sin(90)*sin(\theta_5), -sin(90)*cos(\theta_5), cos(90), 0],
[                     0,                      0,       0, 1]])

In [21]:
p90 = sympy.pi/2
n90 = -p90

In [22]:
p90

pi/2

In [25]:
T45s = robotics_sympy.DH(n90,0,th5s,0)
T45s

Matrix([
[ cos(\theta_5), -sin(\theta_5), 0, 0],
[             0,              0, 1, 0],
[-sin(\theta_5), -cos(\theta_5), 0, 0],
[             0,              0, 0, 1]])

In [26]:
T56s = robotics_sympy.DH(p90,0,th6s,Gs)
T56s

Matrix([
[cos(\theta_6), -sin(\theta_6),  0,  0],
[            0,              0, -1, -G],
[sin(\theta_6),  cos(\theta_6),  0,  0],
[            0,              0,  0,  1]])

**Note:** According to the DH table we are using, $O_6$ is at the tip.

In [27]:
TWtip_sym = TW4s @ T45s @ T56s

In [28]:
TWtip_sym

Matrix([
[-sin(\theta_4)*sin(\theta_6) + cos(\theta_4)*cos(\theta_5)*cos(\theta_6), -sin(\theta_4)*cos(\theta_6) - sin(\theta_6)*cos(\theta_4)*cos(\theta_5), sin(\theta_5)*cos(\theta_4), G*sin(\theta_5)*cos(\theta_4)],
[ sin(\theta_4)*cos(\theta_5)*cos(\theta_6) + sin(\theta_6)*cos(\theta_4), -sin(\theta_4)*sin(\theta_6)*cos(\theta_5) + cos(\theta_4)*cos(\theta_6), sin(\theta_4)*sin(\theta_5), G*sin(\theta_4)*sin(\theta_5)],
[                                            -sin(\theta_5)*cos(\theta_6),                                              sin(\theta_5)*sin(\theta_6),               cos(\theta_5),               G*cos(\theta_5)],
[                                                                       0,                                                                        0,                           0,                             1]])

In [29]:
TWtip_sym.simplify()

In [30]:
TWtip_sym

Matrix([
[-sin(\theta_4)*sin(\theta_6) + cos(\theta_4)*cos(\theta_5)*cos(\theta_6), -sin(\theta_4)*cos(\theta_6) - sin(\theta_6)*cos(\theta_4)*cos(\theta_5), sin(\theta_5)*cos(\theta_4), G*sin(\theta_5)*cos(\theta_4)],
[ sin(\theta_4)*cos(\theta_5)*cos(\theta_6) + sin(\theta_6)*cos(\theta_4), -sin(\theta_4)*sin(\theta_6)*cos(\theta_5) + cos(\theta_4)*cos(\theta_6), sin(\theta_4)*sin(\theta_5), G*sin(\theta_4)*sin(\theta_5)],
[                                            -sin(\theta_5)*cos(\theta_6),                                              sin(\theta_5)*sin(\theta_6),               cos(\theta_5),               G*cos(\theta_5)],
[                                                                       0,                                                                        0,                           0,                             1]])

## Solve for wrist angles

$$^W_{tip}\mathbf{T}_{\textrm{numeric}} \; = \; ^W_{tip}\mathbf{T}_{\textrm{symbolic}}$$

## Final Verification

Use the DH table and multiply all the $^{i-1}_i\mathbf{T}$ matrices together

i|$\alpha$|$a$|$\theta$|d
-|--------|----|--------|-------------
1|0|0|$\theta_1$|A
2|90|0|$\theta_2$|0
3|0|C|$\theta_3$|D-B
4|90|E|th4|F
5|-90|0|th5|0
6|90|0|th6|G