# Rotation Matrix Intro Sign Question

### Standard Imports

In [10]:
import matplotlib.pyplot as plt
import numpy as np
#from numpy import sin, cos, tan, pi
import robotics
from robotics import Rz, Ry, Rz, sind, cosd, DH
rtd = 180/np.pi
dtr = np.pi/180

### Note

If the `robotics` import fails, install Dr. Krauss' `robotics` module using `pip`:

In [ ]:
pip install robotics

## Question

What happens if we naively "google" rotation matrix and appy it to this problem?

Assume we want to use 

$${P}_{rotated} = \mathbf{R} \cdot {P}_{original}$$

<img src="https://faculty.gvsu.edu/kraussry/445_images/chapter_2/rotation_matrix_sign_question.png" width=400px>

## Expected Answer

In [14]:
P_B_x = 4*cosd(30)
P_B_x

np.float64(3.464101615137755)

In [16]:
P_B_y = -4*sind(30)
P_B_y

np.float64(-1.9999999999999998)

### Python Questions

How do we code that up?

- how do we create the vector $P_{original}$?
- how do we find $\mathbf{R}$?
- how do we do matrix multiplication in Python?

In [3]:
P = np.array([4,0,0])
P

array([4, 0, 0])

In [4]:
R = robotics.Rz(30)
R

array([[ 0.8660254, -0.5      ,  0.       ],
       [ 0.5      ,  0.8660254,  0.       ],
       [ 0.       ,  0.       ,  1.       ]])

## This is a level 2 header

- this bullet
    - this is a sub bullet
- this is inline math: $\theta$

This is an equation:

$$^AP = \; ^A_B\mathbf{R} \cdot ^BP$$ 

### Note

This is not matrix multiplication in python (**don't do this**)

In [5]:
R*P

array([[ 3.46410162, -0.        ,  0.        ],
       [ 2.        ,  0.        ,  0.        ],
       [ 0.        ,  0.        ,  0.        ]])

### Either of these is correct:

In [6]:
np.dot(R,P)

array([3.46410162, 2.        , 0.        ])

In [7]:
R@P

array([3.46410162, 2.        , 0.        ])

## Issues

- sign on $Y$ term is wrong
- `robotics.Rz` gives $^A_B\mathbf{R}$
- we need $^B_A\mathbf{R}$
    - because we know $^AP$
 
$$^BP = \; ^B_A\mathbf{R} \cdot ^AP$$

## Possible Sign Issues in Rotation Matrix Problems

- is the rotation positive or negative?
- are we mapping from $A$ to $B$ or $B$ to $A$?
    - did our internet search or AI give us $^A_B\mathbf{R}$ or $^B_A\mathbf{R}$?
        - how do we know which one we need?

## Letting the notation guide us

- if we follow the notation, do we know $^A P$ or $^B P$?
- do we need $^A_B\mathbf{R}$ or $^B_A\mathbf{R}$?
- does knowing which one I need *really* help me?
- which one did googling or `robotics.Rz` give me?

## Sign Checking

- how do I check the signs of a rotation matrix?